Mobile portfolio2
KayLemba/MyPortfolio2 pull request #2
Opened 2021-08-17 12:34 UTC by KayLemba

In this project I created a cards section and an about me section I also did the following:
1. Add cards section and About me section to index.html file
2. Add new styling to styles.css file
3. Update READ.md file
4. Add new screenshot of workflow

2021-08-17 14:03 UTC, Elbie-em requested changes
## STATUS: CHANGES REQUIRED 🟡  ♻️

Hi @KayLemba,  you have really done a great job so far, I like how you are coming close to the actual design provided in the requirements, however, there are some issues that you still need to work on in order to have this project approved, but you are almost there! Check my comments below ⬇️  for more details

Keep on with the hard work 💪  , Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Kindly submit another review request once done and please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._


> Elbie Moonga (Part-time TSE)

> Github (@Elbie-em)
> Slack (Elbie Moonga)
> Twitter ([@ElbieEm](https://twitter.com/ElbieEm))
> LinkedIn([Elbie Moonga](https://www.linkedin.com/in/elbiemoonga/))

2021-08-20 19:36 UTC, KayLemba commented on index.html
> +    <section class="cards-section">
Done

2021-08-20 19:37 UTC, KayLemba commented on index.html
> +        </li>
Done

2021-08-20 19:37 UTC, KayLemba commented on index.html
> +    </section>
done

2021-08-20 19:38 UTC, KayLemba commented on index.html
> +            </ul>
done

2021-08-20 21:35 UTC, barackm approved these changes
Hi @KayLemba, 👋 

# STATUS: Approved  🎉 
Your project is complete!  There is nothing else to say other than... it's time to merge it
Congratulations! 🎉  🎉 🎉 

![](https://media.giphy.com/media/vmtxnxveVUodG/giphy.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-20 21:41 UTC, merged

2021-08-20 21:47 UTC, KayLemba commented
Thank you, I really had it rough trying to correct this work. I'm glad I got it done.